### ISSUE TITLE
Question about generating initramfs 

### ISSUE THREAD

**Issue by toolboc** [clbr/n64bootloader#1]
Hi there,

I'm interested in rebuilding this project from scratch and having a great time learning along the way.  I've made a bit of headway after realizing that the toolchain used in this project is an earlier version of [libdragon](https://github.com/DragonMinded/libdragon/). I've got the preliminary portions of the bootloader compilation sorted and am now working on building the kernel using the n64 branch of your Linux fork at https://github.com/clbr/linux/tree/n64.

After using [musl-cross-make](https://github.com/richfelker/musl-cross-make) to build the mips64-linux-musln32 tools / libraries, I am able to successfully build the kernel with `make ARCH=mips CROSS_COMPILE=mips64-linux-musln32-` but am having trouble creating a working initramfs.  The n64-kernel-config references an [initramfs to be picked up at "/tmp/n64root.cpio"](https://github.com/clbr/n64bootloader/blob/master/n64linux/n64-kernel-config#L117).  I'm curious how I might go about recreating this from scratch, I assume this would contain the init entrypoint for busybox and other components listed at the bottom of this [README](https://github.com/clbr/n64bootloader/tree/master/n64linux)?

It looks like this can be accomplished by creating a directory structure locally and simply running:
```ls | cpio -ov > /tmp/n64root.cpio```

I've built a custom hello world application to serve as "init" according to https://landley.net/writing/rootfs-howto.html, but it seems that this method of creating the cpio results in a kernel panice with message "no cpio magic".  Any chance you might be able to offer some clues or guidance on how the built-in initramfs was produced?

**Comment by clbr** [comment]
```
mkdir tmpdir
cd tmpdir
mips64-linux-musln32-gcc -o init /path/to/hello.c -static
find | cpio -o -H newc > /tmp/n64root.cpio
```

That should get you a hello world init. How you then proceed with the initramfs and whether you use the n64 cart at all is up to your preference. I used a minimal initramfs and put squashfs to the cart to save RAM, but if your use case is "one binary", having it statically built in the initramfs may work ok (since it needs to be loaded to RAM to run it anyway).

You can extract the initramfs I used from my kernel binary to have a look (extract the kernel first from the z64 using the size and position, then use the kernel's initramfs extraction script).

**Comment by toolboc** [comment]
That worked!  Thank you!

It would be totally rad if you might be able to include more details on the initramfs and squashfs creation.  While it is cool that we can pull down a pre-built kernel, it'd be extremely useful to have the ability to use this project as a custom launcher for other interesting applications (Emulators, Games, etc.) that might be able to fit into the 8MB RAM space.  Anything that could help others replicate your processes would be extremely valuable!
