### ISSUE TITLE
Accessories to support 

### ISSUE THREAD

**Issue by upintheairsheep** [clbr/n64bootloader#6]
Hello, do you plan on adding any more accessory support to this port as drivers?
	1.	The controller pak (a memory card-like controller save system) should be added as a read-write block device.	 
        2.	The rumble pak should be supported as an amendment to the N64 controller driver.
	3.	The transfer pak should be supported as a block device that supports the GameBoy ROM and Save data file 
	5.	The 64DD should be supported as a block device, as well as the real time clock inside of it, and the read-only library of fonts and audio
	6.	The Nintendo 64 mouse is the same thing as the controller joystick if I am right
	7.	The VRU should be supported
	8.	The Randnet keyboard should be supported as well for sure if not already.
	10.	The doctor V64 should be supported as a CD-ROM drive

**Comment by upintheairsheep** [comment]
I apologize if I sound demanding, but this is more of a “later on” todo list, and additionally audio should be supported if it hasn’t already been supported.

**Comment by clbr** [comment]
The cart, controller and audio are already supported. There are no plans currently to support additional peripherals. It is all open source, so you are welcome to add such support yourself.
